# Autogenerated wrapper script for IRBEM_jll for armv6l-linux-musleabihf-libgfortran3
export libirbem

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("IRBEM")
JLLWrappers.@declare_library_product(libirbem, "libirbem.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libirbem,
        "lib/libirbem.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
