# Autogenerated wrapper script for IRBEM_jll for i686-w64-mingw32-libgfortran4
export libirbem

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("IRBEM")
JLLWrappers.@declare_library_product(libirbem, "libirbem.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libirbem,
        "bin\\libirbem.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
